[tool.poetry]
name = "clai"
version = "0.1.0"
description = ""
authors = ["Koen Klinkers <k.klinkers@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.3.9"
rich = "^13.3.4"
prompt-toolkit = "^3.0.38"
typer = "^0.7.0"
pyperclip = "^1.8.2"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
